# Generated by Django 4.2.4 on 2023-09-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
